DynamicBooking/Controllers/CreateController.cs
using DynamicBooking.UseCases.CreateForm;
using DynamicBooking.ViewModels;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace DynamicBooking.Controllers;

[Route("create")]
public class CreateController : Controller
{
    private readonly IMediator mediator;

    public CreateController(IMediator mediator)
    {
        this.mediator = mediator;
    }

    [HttpPost()]
    public async Task<IActionResult> Create(FormViewModel model)
    {
        var command = new CreateFormCommand(model);

        var eventActions = await mediator.Send(command);

        return RedirectToAction("References", "References", eventActions);
    }

    [HttpGet()]
    public IActionResult Create()
    {
        return View(new FormViewModel());
    }
}

DynamicBooking/Controllers/HomeController.cs
using DynamicBooking.ViewModels;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace DynamicBooking.Controllers;

public class HomeController : Controller
{
    private readonly IMediator mediator;

    public HomeController(IMediator mediator)
    {
        this.mediator = mediator;
    }

    public IActionResult Index()
    {
        return View(new IndexViewModel());
    }
}

DynamicBooking/Views/Home/Index.cshtml
@model IndexViewModel

<div class="d-flex justify-content-center align-items-center vh-100">
    <div class="bg-light flex-column p-5">
        <h1>Сервис динамического бронирования</h1>
        <form class="row align-items-center" asp-action="create" asp-controller="Create" method="get">
            <button type="submit" class="btn btn-primary">Создать форму</button>
        </form>
    </div>
</div>